project_id = "nvmvyjajmasaksyffemu"

[functions.consultoria-ai]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.generate-product-video]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.heygen-avatar]
verify_jwt = false

[functions.prompt-from-screenshot]
verify_jwt = false

[functions.analyze-person-photo]
verify_jwt = false

[functions.classify-image-type]
verify_jwt = false

[functions.create-prompt-purchase]
verify_jwt = false

[functions.ensure-admin-user]
verify_jwt = false

[functions.generate-prompt-image]
verify_jwt = false

[functions.manage-prompt]
verify_jwt = false

[functions.validate-generated-image]
verify_jwt = false


[functions.create-mercadopago-payment]
verify_jwt = false

[functions.verify-mercadopago-payment]
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.verify-asaas-payment]
verify_jwt = false
