
-- Add comprehensive KPI and classification columns to influencers table
ALTER TABLE public.influencers
  ADD COLUMN IF NOT EXISTS avatar_url text,
  ADD COLUMN IF NOT EXISTS views_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_likes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_comments integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_shares integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_views integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS audience_male_pct numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS audience_female_pct numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS audience_age_range text DEFAULT '18-34',
  ADD COLUMN IF NOT EXISTS location text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS country text DEFAULT 'Brasil',
  ADD COLUMN IF NOT EXISTS content_type text DEFAULT 'influencer',
  ADD COLUMN IF NOT EXISTS tier text DEFAULT 'micro',
  ADD COLUMN IF NOT EXISTS niche text,
  ADD COLUMN IF NOT EXISTS secondary_niche text,
  ADD COLUMN IF NOT EXISTS languages text[] DEFAULT '{pt-BR}',
  ADD COLUMN IF NOT EXISTS platforms text[] DEFAULT '{instagram}',
  ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_available boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS rating numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_campaigns integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completion_rate numeric DEFAULT 100,
  ADD COLUMN IF NOT EXISTS avg_response_time_hours integer DEFAULT 24,
  ADD COLUMN IF NOT EXISTS price_per_story numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_per_reel numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_per_video numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_per_live numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS monthly_reach integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpm numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpe numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS website_url text,
  ADD COLUMN IF NOT EXISTS media_kit_url text,
  ADD COLUMN IF NOT EXISTS notes text;
